### ISSUE TITLE
Missing deployment / runtime related documentation

### ISSUE THREAD

**Issue by hms** [fractaledmind/acidic_job#71]
I couldn't find any documentation on deployment and runtime related issues such as: how to start AJ, how it manages queues, monitoring, etc.   Is it possible I missed the details somewhere?

If not, I think the lack of this information would stop people from even trying AJ, which is a shame as it's a very, very interesting project that I would have loved to use in my application.

**Comment by fractaledmind** [comment]
Hey @hms. Somehow my GitHub notifications are messed up and I never saw this message. Apologies.

To your issue: `AcidicJob` is a gem that wraps up a collection of best-practices for making ActiveJobs more resilient. As such, it gets the benefit of piggy-backing on your application's existing ActiveJob deployment and backend. It doesn't matter what backend you are using to manage your ActiveJob queues, as `AcidicJob` is purely a Ruby mixin for your job classes.

This [Usage](https://github.com/fractaledmind/acidic_job#usage) section in the README is truly all that you need to get it setup, because you simply need to mix the module into your base job, and then you use the provided methods as described in the various feature sections.

Hopefully this clears up the scope of the project, but if you have further questions, let me know.

**Comment by hms** [comment]
@fractaledmind 

Thank you for taking the time to respond.  

I have a use-case that really would become a lot simpler and significantly more robust with AcidicJob.  I'll be excitedly exploring how AcidicJob plays with GoodJob in the next week or two.

hms

**Comment by fractaledmind** [comment]
@hms: Curious if you are on the other side of integrating AcidicJob into your application with GoodJob as your job backend? I'd love to hear about how that went, if there were any sharp corners, or if you think there are ways to improve the docs with some of your insights?

**Comment by hms** [comment]
@fractaledmind 

Hi.  
At the end of the day and with looming deployment deadlines, we decided to not take on an additional project dependency. It turns out after some deeper thought and with our requirements, we could 'simulate' AcidicJobs
functionality adequately to launch.  

Our expectation is to revisit AcidJob in the next couple of months once things settle down.
